#!/bin/bash
echo 'python ../../../dlopt/tools/main.py --config config/0.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/0.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/1.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/1.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/2.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/2.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/3.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/3.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/4.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/4.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/5.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/5.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/6.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/6.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/7.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/7.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/8.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/8.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/9.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/9.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/10.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/10.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/11.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/11.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/12.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/12.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/13.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/13.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/14.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/14.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/15.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/15.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/16.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/16.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/17.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/17.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/18.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/18.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/19.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/19.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/20.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/20.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/21.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/21.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/22.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/22.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/23.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/23.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/24.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/24.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/25.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/25.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/26.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/26.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/27.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/27.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/28.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/28.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/29.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/29.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/30.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/30.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/31.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/31.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/32.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/32.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/33.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/33.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/34.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/34.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/35.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/35.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/36.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/36.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/37.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/37.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/38.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/38.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/39.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/39.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/40.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/40.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/41.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/41.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/42.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/42.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/43.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/43.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/44.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/44.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/45.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/45.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/46.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/46.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/47.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/47.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/48.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/48.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/49.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/49.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/50.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/50.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/51.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/51.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/52.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/52.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/53.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/53.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/54.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/54.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/55.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/55.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/56.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/56.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/57.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/57.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/58.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/58.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/59.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/59.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/60.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/60.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/61.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/61.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/62.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/62.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/63.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/63.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/64.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/64.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/65.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/65.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/66.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/66.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/67.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/67.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/68.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/68.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/69.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/69.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/70.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/70.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/71.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/71.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/72.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/72.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/73.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/73.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/74.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/74.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/75.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/75.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/76.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/76.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/77.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/77.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/78.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/78.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/79.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/79.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/80.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/80.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/81.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/81.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/82.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/82.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/83.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/83.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/84.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/84.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/85.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/85.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/86.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/86.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/87.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/87.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/88.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/88.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/89.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/89.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/90.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/90.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/91.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/91.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/92.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/92.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/93.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/93.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/94.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/94.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/95.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/95.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/96.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/96.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/97.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/97.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/98.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/98.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/99.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/99.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/100.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/100.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/101.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/101.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/102.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/102.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/103.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/103.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/104.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/104.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/105.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/105.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/106.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/106.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/107.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/107.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/108.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/108.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/109.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/109.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/110.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/110.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/111.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/111.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/112.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/112.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/113.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/113.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/114.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/114.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/115.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/115.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/116.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/116.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/117.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/117.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/118.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/118.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/119.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/119.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/120.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/120.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/121.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/121.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/122.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/122.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/123.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/123.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/124.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/124.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/125.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/125.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/126.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/126.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/127.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/127.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/128.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/128.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/129.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/129.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/130.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/130.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/131.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/131.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/132.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/132.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/133.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/133.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/134.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/134.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/135.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/135.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/136.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/136.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/137.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/137.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/138.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/138.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/139.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/139.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/140.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/140.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/141.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/141.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/142.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/142.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/143.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/143.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/144.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/144.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/145.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/145.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/146.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/146.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/147.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/147.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/148.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/148.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/149.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/149.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/150.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/150.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/151.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/151.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/152.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/152.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/153.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/153.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/154.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/154.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/155.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/155.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/156.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/156.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/157.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/157.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/158.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/158.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/159.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/159.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/160.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/160.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/161.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/161.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/162.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/162.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/163.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/163.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/164.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/164.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/165.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/165.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/166.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/166.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/167.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/167.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/168.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/168.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/169.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/169.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/170.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/170.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/171.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/171.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/172.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/172.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/173.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/173.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/174.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/174.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/175.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/175.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/176.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/176.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/177.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/177.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/178.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/178.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/179.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/179.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/180.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/180.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/181.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/181.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/182.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/182.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/183.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/183.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/184.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/184.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/185.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/185.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/186.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/186.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/187.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/187.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/188.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/188.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/189.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/189.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/190.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/190.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/191.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/191.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/192.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/192.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/193.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/193.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/194.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/194.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/195.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/195.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/196.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/196.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/197.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/197.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/198.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/198.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/199.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/199.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/200.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/200.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/201.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/201.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/202.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/202.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/203.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/203.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/204.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/204.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/205.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/205.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/206.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/206.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/207.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/207.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/208.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/208.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/209.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/209.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/210.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/210.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/211.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/211.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/212.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/212.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/213.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/213.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/214.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/214.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/215.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/215.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/216.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/216.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/217.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/217.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/218.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/218.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/219.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/219.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/220.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/220.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/221.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/221.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/222.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/222.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/223.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/223.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/224.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/224.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/225.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/225.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/226.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/226.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/227.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/227.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/228.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/228.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/229.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/229.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/230.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/230.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/231.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/231.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/232.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/232.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/233.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/233.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/234.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/234.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/235.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/235.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/236.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/236.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/237.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/237.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/238.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/238.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/239.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/239.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/240.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/240.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/241.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/241.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/242.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/242.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/243.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/243.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/244.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/244.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/245.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/245.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/246.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/246.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/247.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/247.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/248.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/248.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/249.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/249.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/250.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/250.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/251.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/251.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/252.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/252.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/253.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/253.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/254.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/254.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/255.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/255.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/256.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/256.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/257.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/257.json --verbose=2
echo 'python ../../../dlopt/tools/main.py --config config/258.json --verbose=2' 
python ../../../dlopt/tools/main.py --config config/258.json --verbose=2

